//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class abstract_user
{
    public int id { get; set; }
    public string name { get; set; }
    public string familyName { get; set; }
    public string email { get; set; }
    public string address { get; set; }
    public string gender { get; set; }
    public Nullable<byte> status { get; set; }
    public string password { get; set; }
    public string role { get; set; }
    public string company { get; set; }
    public string userPhoneNumber { get; set; }
}

public partial class @case
{
    public int caseId { get; set; }
    public Nullable<int> caseAbstractUserId { get; set; }
    public string operatorComments { get; set; }
    public Nullable<byte> statusCase { get; set; }
    public string creation_date { get; set; }
    public string creation_time { get; set; }
    public Nullable<byte> needsTowingService { get; set; }
}

public partial class client
{
    public int abstractUserId { get; set; }
    public string insuranceCompanyName { get; set; }
    public Nullable<int> licensePlate { get; set; }
    public string carCategory { get; set; }
    public string carModel { get; set; }
    public string originalTowingDestination { get; set; }
    public Nullable<int> insurancePolicyNum { get; set; }
    public Nullable<int> clientDrivingLicenseNumber { get; set; }
    public string policyEndDate { get; set; }
    public string updates { get; set; }
    public Nullable<int> emergencyReportId { get; set; }
    public string carOwnerName { get; set; }
    public Nullable<int> carOwnerId { get; set; }
    public Nullable<int> carLicenseNumber { get; set; }
    public string insuranceAgentName { get; set; }
    public Nullable<int> insuranceAgentPhoneNum { get; set; }
    public string carManufactureYear { get; set; }

    public virtual client client1 { get; set; }
    public virtual client client2 { get; set; }
}

public partial class emergencyReport
{
    public Nullable<int> caseCaseId { get; set; }
    public string date { get; set; }
    public string hour { get; set; }
    public string location { get; set; }
    public string towing_destination { get; set; }
    public string accident_witness_name { get; set; }
    public Nullable<int> accident_witness_phone { get; set; }
    public string comments { get; set; }
    public Nullable<byte> callForTowing { get; set; }
    public int reportID { get; set; }
    public int clientAbstractUserId { get; set; }
}

public partial class third_party
{
    public int emergencyReportId { get; set; }
    public string driverName { get; set; }
    public Nullable<int> driverId { get; set; }
    public string carOwnerName { get; set; }
    public Nullable<int> carOwnerId { get; set; }
    public Nullable<int> licensePlateNumber { get; set; }
    public string carCategory { get; set; }
    public string carModel { get; set; }
    public string carColor { get; set; }
    public Nullable<int> drivingLicenseNumber { get; set; }
    public string insuranceCompanyName { get; set; }
    public Nullable<int> insurancePolicyNumber { get; set; }
    public string address { get; set; }
    public Nullable<int> phoneNumber { get; set; }
    public string insuranceAgentName { get; set; }
    public Nullable<int> insuranceAgentPhone { get; set; }
    public Nullable<int> yearOfManufacture { get; set; }
}
