//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abstract_user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string familyName { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public Nullable<byte> status { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string company { get; set; }
        public string userPhoneNumber { get; set; }
    }
}
