//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appraisers
    {
        public int appraiserID { get; set; }
        public Nullable<int> taskCount { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string region { get; set; }
    }
}
