//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appraiserReports
    {
        public int appraiserReportId { get; set; }
        public Nullable<int> emergencyReportID { get; set; }
        public Nullable<int> appraiserId { get; set; }
        public string summaryDamage1 { get; set; }
        public Nullable<int> amount1 { get; set; }
        public byte[] picture1 { get; set; }
        public string summaryDamage2 { get; set; }
        public Nullable<int> amount2 { get; set; }
        public byte[] picture2 { get; set; }
        public Nullable<int> sumTotal { get; set; }
        public string comments { get; set; }
        public string summaryDamage3 { get; set; }
        public Nullable<int> amount3 { get; set; }
        public byte[] picture3 { get; set; }
        public string summaryDamage4 { get; set; }
        public Nullable<int> amount4 { get; set; }
        public byte[] picture4 { get; set; }
        public string summaryDamage5 { get; set; }
        public Nullable<int> amount5 { get; set; }
        public byte[] picture5 { get; set; }
    }
}
