//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appraiserTaskList
    {
        public int appraID { get; set; }
        public int taskID { get; set; }
        public string location { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> status { get; set; }
        public string clientName { get; set; }
        public string clientPhone { get; set; }
        public string destinationJob { get; set; }
        public string date { get; set; }
        public Nullable<int> reportId { get; set; }
    }
}
