//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rtesEntities1 : DbContext
    {
        public rtesEntities1()
            : base("name=rtesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abstract_user> abstract_user { get; set; }
        public virtual DbSet<appraiserReports> appraiserReport { get; set; }
        public virtual DbSet<appraisers> appraiser { get; set; }
        public virtual DbSet<appraiserTaskLists> appraiserTaskList { get; set; }
        public virtual DbSet<clients> client { get; set; }
        public virtual DbSet<emergencyReports> emergencyReport { get; set; }
        public virtual DbSet<estimationForms> estimationForm { get; set; }
        public virtual DbSet<images> image { get; set; }
        public virtual DbSet<messagesTables> messagesTable { get; set; }
        public virtual DbSet<taskLists> taskList { get; set; }
        public virtual DbSet<third_party> third_party { get; set; }
        public virtual DbSet<towingReportForms> towingReportForm { get; set; }
        public virtual DbSet<truckDrivers> truckDriver { get; set; }
    }
}
