//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskLists
    {
        public Nullable<int> truckDriverId { get; set; }
        public Nullable<int> reportId { get; set; }
        public int taskId { get; set; }
        public Nullable<int> status { get; set; }
    }
}
