//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class third_party
    {
        public int emergencyReportId { get; set; }
        public string driverName { get; set; }
        public string driverId { get; set; }
        public string carOwnerName { get; set; }
        public string carOwnerId { get; set; }
        public string licensePlateNumber { get; set; }
        public string carCategory { get; set; }
        public string carModel { get; set; }
        public string carColor { get; set; }
        public string drivingLicenseNumber { get; set; }
        public string insuranceCompanyName { get; set; }
        public string insurancePolicyNumber { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string insuranceAgentName { get; set; }
        public string insuranceAgentPhone { get; set; }
        public Nullable<int> yearOfManufacture { get; set; }
    }
}
