//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class towingReportForms
    {
        public int reportID { get; set; }
        public Nullable<int> driverUserID { get; set; }
        public string arrivalTime { get; set; }
        public string date { get; set; }
        public string towingDestinationLocation { get; set; }
        public string comments { get; set; }
    }
}
