//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTESWebProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class truckDriver
    {
        public int abstractUserId { get; set; }
        public Nullable<int> cargo { get; set; }
        public Nullable<bool> availability { get; set; }
        public Nullable<bool> workStatus { get; set; }
        public string location { get; set; }
        public Nullable<int> TasksCounter { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> priority1 { get; set; }
        public Nullable<int> priority2 { get; set; }
        public Nullable<int> priority3 { get; set; }
    }
}
